kind: Deployment
apiVersion: apps/v1
metadata:
  name: osrf-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osrf-test-app
  template:
    metadata:
      labels:
        app: osrf-test-app
    spec:
      containers:
        - name: osrf-test
          image: python-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: osrf-test
spec:
ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
selector:
  app: osrf-test-app
